onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /nios_sys_tb/nios_sys_inst/clk_clk
add wave -noupdate /nios_sys_tb/nios_sys_inst/reset_reset_n
add wave -noupdate -radix decimal -childformat {{{/nios_sys_tb/nios_sys_inst/dma_0/status[4]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/status[3]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/status[2]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/status[1]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/status[0]} -radix decimal}} -expand -subitemconfig {{/nios_sys_tb/nios_sys_inst/dma_0/status[4]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/status[3]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/status[2]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/status[1]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/status[0]} {-radix decimal}} /nios_sys_tb/nios_sys_inst/dma_0/status
add wave -noupdate -radix decimal -childformat {{{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[17]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[16]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[15]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[14]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[13]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[12]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[11]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[10]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[9]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[8]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[7]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[6]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[5]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[4]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[3]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[2]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[1]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[0]} -radix decimal}} -expand -subitemconfig {{/nios_sys_tb/nios_sys_inst/dma_0/readaddress[17]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[16]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[15]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[14]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[13]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[12]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[11]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[10]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[9]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[8]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[7]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[6]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[5]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[4]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[3]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[2]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[1]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/readaddress[0]} {-radix decimal}} /nios_sys_tb/nios_sys_inst/dma_0/readaddress
add wave -noupdate -radix decimal -childformat {{{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[17]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[16]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[15]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[14]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[13]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[12]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[11]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[10]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[9]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[8]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[7]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[6]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[5]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[4]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[3]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[2]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[1]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[0]} -radix decimal}} -expand -subitemconfig {{/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[17]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[16]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[15]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[14]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[13]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[12]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[11]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[10]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[9]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[8]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[7]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[6]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[5]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[4]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[3]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[2]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[1]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/writeaddress[0]} {-radix decimal}} /nios_sys_tb/nios_sys_inst/dma_0/writeaddress
add wave -noupdate -radix decimal -childformat {{{/nios_sys_tb/nios_sys_inst/dma_0/length[15]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[14]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[13]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[12]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[11]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[10]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[9]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[8]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[7]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[6]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[5]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[4]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[3]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[2]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[1]} -radix decimal} {{/nios_sys_tb/nios_sys_inst/dma_0/length[0]} -radix decimal}} -subitemconfig {{/nios_sys_tb/nios_sys_inst/dma_0/length[15]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[14]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[13]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[12]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[11]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[10]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[9]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[8]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[7]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[6]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[5]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[4]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[3]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[2]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[1]} {-radix decimal} {/nios_sys_tb/nios_sys_inst/dma_0/length[0]} {-radix decimal}} /nios_sys_tb/nios_sys_inst/dma_0/length
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5145047403 ps} 0} {{Cursor 2} {1670000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 392
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4768019335 ps} {5442488151 ps}
